# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truffe', '0002_auto_20201104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcreditcard',
            name='name',
            field=models.CharField(default='---', max_length=255, unique=True),
        ),
    ]
