# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_main', '0003_auto_20201104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingerror',
            name='linked_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_main.AccountingLine', verbose_name='Ligne liée'),
        ),
        migrations.AlterField(
            model_name='accountingerror',
            name='status',
            field=models.CharField(choices=[('0_drafting', 'Établisement du problème'), ('1_fixing', 'En attente de correction'), ('2_fixed', 'Correction effectuée')], default='0_drafting', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountingerrorlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='accountingerrorlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingerrormessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingerrorviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingline',
            name='status',
            field=models.CharField(choices=[('0_imported', 'En attente'), ('1_validated', 'Validé'), ('2_error', 'Erreur')], default='0_imported', max_length=255),
        ),
        migrations.AlterField(
            model_name='accountinglinelogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='accountinglinelogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountinglineviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budget',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Titre du budget'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('0_correct', 'A corriger'), ('1_submited', 'Budget soumis'), ('1_private', 'Budget privé'), ('2_treated', 'Budget validé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='budgetlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='budgetlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
