# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberset',
            name='generated_accred_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.Role', verbose_name='Accréditation générée pour les membres'),
        ),
        migrations.AlterField(
            model_name='memberset',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='memberset',
            name='status',
            field=models.CharField(choices=[('0_preparing', 'En préparation'), ('1_active', 'Actif'), ('2_archived', 'Archivé')], default='0_preparing', max_length=255),
        ),
        migrations.AlterField(
            model_name='membersetlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='membersetlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membersetviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
