# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_tools', '0003_auto_20201104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Titre du journal de caisse'),
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('0_correct', 'Corrections nécessaires'), ('1_unit_validable', 'Attente accord unité'), ('2_agep_validable', 'Attente vérification secrétariat'), ('3_agep_sig1', 'Attente signature CdD 1'), ('3_agep_sig2', 'Attente signature CdD 2'), ('4_accountable', 'A comptabiliser'), ('5_in_accounting', 'En comptabilisation'), ('6_archived', 'Archivé'), ('6_canceled', 'Annulé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='cashbookfile',
            name='file',
            field=models.FileField(upload_to='uploads/_generic/CashBook/'),
        ),
        migrations.AlterField(
            model_name='cashbookfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbookline',
            name='helper',
            field=models.CharField(choices=[('0_withdraw', "J'ai fait un retrait cash : "), ('1_deposit', "J'ai fait un versement à la banque : "), ('2_sell', "J'ai vendu quelque chose : "), ('3_invoice', "J'ai payé une facture avec la caisse : "), ('4_buy', "J'ai acheté quelque chose avec la caisse : "), ('5_reimburse', "J'ai remboursé quelqu'un avec la caisse : "), ('6_input', 'Je fais un Crédit manuel : '), ('7_output', 'Je fais un Débit manuel : ')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cashbooklogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='cashbooklogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cashbookviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Titre de la note de frais'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('0_correct', 'Corrections nécessaires'), ('1_unit_validable', 'Attente accord unité'), ('2_agep_validable', 'Attente vérification secrétariat'), ('3_agep_sig1', 'Attente signature CdD 1'), ('3_agep_sig2', 'Attente signature CdD 2'), ('4_accountable', 'A comptabiliser'), ('5_in_accounting', 'En comptabilisation'), ('6_archived', 'Archivé'), ('6_canceled', 'Annulé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='expenseclaimfile',
            name='file',
            field=models.FileField(upload_to='uploads/_generic/ExpenseClaim/'),
        ),
        migrations.AlterField(
            model_name='expenseclaimfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseclaimlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='expenseclaimlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expenseclaimviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialprovider',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Nom du fournisseur'),
        ),
        migrations.AlterField(
            model_name='financialproviderlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='financialproviderlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialproviderviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internaltransfer',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Raison du transfert'),
        ),
        migrations.AlterField(
            model_name='internaltransfer',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('1_agep_validable', 'Attente accord AGEPoly'), ('2_accountable', 'A comptabiliser'), ('3_archived', 'Archivé'), ('3_canceled', 'Annulé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='internaltransferlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='internaltransferlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internaltransferviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='greetings',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Salutations'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('0_preparing', 'En préparation'), ('0_correct', 'Corrections nécessaires'), ('1_need_bvr', "En attente d'un numéro BVR"), ('2_ask_accord', 'Attente Accord AGEPoly'), ('2_accord', 'Attente Envoi'), ('3_sent', 'Envoyée / paiement en attente'), ('4_archived', 'Archivée / Paiement reçu'), ('5_canceled', 'Annulée')], default='0_preparing', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicelogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='invoicelogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerinvoice',
            name='currency',
            field=models.CharField(choices=[('AFN', 'AFN'), ('EUR', 'EUR'), ('ALL', 'ALL'), ('DZD', 'DZD'), ('USD', 'USD'), ('AOA', 'AOA'), ('XCD', 'XCD'), ('ARS', 'ARS'), ('AMD', 'AMD'), ('AWG', 'AWG'), ('AUD', 'AUD'), ('AZN', 'AZN'), ('BSD', 'BSD'), ('BHD', 'BHD'), ('BDT', 'BDT'), ('BBD', 'BBD'), ('BYN', 'BYN'), ('BZD', 'BZD'), ('XOF', 'XOF'), ('BMD', 'BMD'), ('INR', 'INR'), ('BTN', 'BTN'), ('BOB', 'BOB'), ('BOV', 'BOV'), ('BAM', 'BAM'), ('BWP', 'BWP'), ('NOK', 'NOK'), ('BRL', 'BRL'), ('BND', 'BND'), ('BGN', 'BGN'), ('BIF', 'BIF'), ('CVE', 'CVE'), ('KHR', 'KHR'), ('XAF', 'XAF'), ('CAD', 'CAD'), ('KYD', 'KYD'), ('CLP', 'CLP'), ('CLF', 'CLF'), ('CNY', 'CNY'), ('COP', 'COP'), ('COU', 'COU'), ('KMF', 'KMF'), ('CDF', 'CDF'), ('NZD', 'NZD'), ('CRC', 'CRC'), ('HRK', 'HRK'), ('CUP', 'CUP'), ('CUC', 'CUC'), ('ANG', 'ANG'), ('CZK', 'CZK'), ('DKK', 'DKK'), ('DJF', 'DJF'), ('DOP', 'DOP'), ('EGP', 'EGP'), ('SVC', 'SVC'), ('ERN', 'ERN'), ('ETB', 'ETB'), ('FKP', 'FKP'), ('FJD', 'FJD'), ('XPF', 'XPF'), ('GMD', 'GMD'), ('GEL', 'GEL'), ('GHS', 'GHS'), ('GIP', 'GIP'), ('GTQ', 'GTQ'), ('GBP', 'GBP'), ('GNF', 'GNF'), ('GYD', 'GYD'), ('HTG', 'HTG'), ('HNL', 'HNL'), ('HKD', 'HKD'), ('HUF', 'HUF'), ('ISK', 'ISK'), ('IDR', 'IDR'), ('IRR', 'IRR'), ('IQD', 'IQD'), ('ILS', 'ILS'), ('JMD', 'JMD'), ('JPY', 'JPY'), ('JOD', 'JOD'), ('KZT', 'KZT'), ('KES', 'KES'), ('KPW', 'KPW'), ('KRW', 'KRW'), ('KWD', 'KWD'), ('KGS', 'KGS'), ('LAK', 'LAK'), ('LBP', 'LBP'), ('LSL', 'LSL'), ('ZAR', 'ZAR'), ('LRD', 'LRD'), ('LYD', 'LYD'), ('CHF', 'CHF'), ('MOP', 'MOP'), ('MKD', 'MKD'), ('MGA', 'MGA'), ('MWK', 'MWK'), ('MYR', 'MYR'), ('MVR', 'MVR'), ('MRU', 'MRU'), ('MUR', 'MUR'), ('MXN', 'MXN'), ('MXV', 'MXV'), ('MDL', 'MDL'), ('MNT', 'MNT'), ('MAD', 'MAD'), ('MZN', 'MZN'), ('MMK', 'MMK'), ('NAD', 'NAD'), ('NPR', 'NPR'), ('NIO', 'NIO'), ('NGN', 'NGN'), ('OMR', 'OMR'), ('PKR', 'PKR'), ('PAB', 'PAB'), ('PGK', 'PGK'), ('PYG', 'PYG'), ('PEN', 'PEN'), ('PHP', 'PHP'), ('PLN', 'PLN'), ('QAR', 'QAR'), ('RON', 'RON'), ('RUB', 'RUB'), ('RWF', 'RWF'), ('SHP', 'SHP'), ('WST', 'WST'), ('STN', 'STN'), ('SAR', 'SAR'), ('RSD', 'RSD'), ('SCR', 'SCR'), ('SLL', 'SLL'), ('SGD', 'SGD'), ('SBD', 'SBD'), ('SOS', 'SOS'), ('SSP', 'SSP'), ('LKR', 'LKR'), ('SDG', 'SDG'), ('SRD', 'SRD'), ('SZL', 'SZL'), ('SEK', 'SEK'), ('CHE', 'CHE'), ('CHW', 'CHW'), ('SYP', 'SYP'), ('TWD', 'TWD'), ('TJS', 'TJS'), ('TZS', 'TZS'), ('THB', 'THB'), ('TOP', 'TOP'), ('TTD', 'TTD'), ('TND', 'TND'), ('TRY', 'TRY'), ('TMT', 'TMT'), ('UGX', 'UGX'), ('UAH', 'UAH'), ('AED', 'AED'), ('USN', 'USN'), ('UYU', 'UYU'), ('UYI', 'UYI'), ('UYW', 'UYW'), ('UZS', 'UZS'), ('VUV', 'VUV'), ('VES', 'VES'), ('VND', 'VND'), ('YER', 'YER'), ('ZMW', 'ZMW'), ('ZWL', 'ZWL')], default='CHF', max_length=3, verbose_name='Devise'),
        ),
        migrations.AlterField(
            model_name='providerinvoice',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Titre de la facture fournisseur'),
        ),
        migrations.AlterField(
            model_name='providerinvoice',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('0_correct', 'Corrections nécessaires'), ('1_unit_validable', 'Attente accord unité'), ('2_agep_validable', 'Attente vérification secrétariat'), ('3_agep_sig1', 'Attente signature CdD 1'), ('3_agep_sig2', 'Attente signature CdD 2'), ('4_accountable', 'A comptabiliser'), ('5_in_accounting', 'En comptabilisation'), ('6_archived', 'Archivé'), ('6_canceled', 'Annulé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='providerinvoicefile',
            name='file',
            field=models.FileField(upload_to='uploads/_generic/ProviderInvoice/'),
        ),
        migrations.AlterField(
            model_name='providerinvoicefile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerinvoicelogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='providerinvoicelogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='providerinvoiceviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subvention',
            name='kind',
            field=models.CharField(blank=True, choices=[('subvention', 'Subvention'), ('sponsorship', 'Sponsoring')], max_length=15, null=True, verbose_name='Type de soutien'),
        ),
        migrations.AlterField(
            model_name='subvention',
            name='linked_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting_main.Budget', verbose_name='Budget annuel lié'),
        ),
        migrations.AlterField(
            model_name='subvention',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Nom du projet'),
        ),
        migrations.AlterField(
            model_name='subvention',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('0_correct', 'A corriger'), ('1_submited', 'Demande soumise'), ('2_treated', 'Demande traitée')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='subventionfile',
            name='file',
            field=models.FileField(upload_to='uploads/_generic/Subvention/'),
        ),
        migrations.AlterField(
            model_name='subventionfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subventionline',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name="Nom de l'évènement"),
        ),
        migrations.AlterField(
            model_name='subventionlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='subventionlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subventionviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='name',
            field=models.CharField(default='---', max_length=255, verbose_name='Raison du retrait'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('1_agep_validable', 'Attente accord AGEPoly'), ('2_withdrawn', 'Prêt à être récupéré'), ('3_used', 'Récupéré / A justifier'), ('4_archived', 'Archivé'), ('4_canceled', 'Annulé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='withdrawalfile',
            name='file',
            field=models.FileField(upload_to='uploads/_generic/Withdrawal/'),
        ),
        migrations.AlterField(
            model_name='withdrawalfile',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawallogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='withdrawallogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawalviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
