# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201104_1311-5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truffeuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Si pas renseigné, utilise la photo EPFL. Si pas de photo EPFL publique, utilise un poney.', null=True, upload_to='uploads/avatars/'),
        ),
        migrations.AlterField(
            model_name='truffeuser',
            name='body',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprivacy',
            name='field',
            field=models.CharField(choices=[('mobile', 'Mobile'), ('adresse', 'Adresse'), ('nom_banque', 'Nom banque'), ('iban_ou_ccp', 'IBAN ou CCP'), ('email_perso', 'Adresse email privée')], max_length=64),
        ),
        migrations.AlterField(
            model_name='userprivacy',
            name='level',
            field=models.CharField(choices=[('prive', 'Privé'), ('groupe', 'Membres de mes groupes'), ('member', 'Accrédités AGEPoly'), ('public', 'Public')], max_length=64),
        ),
        migrations.AlterField(
            model_name='userprivacy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
