# Generated by Django 2.2.18 on 2021-02-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='access',
            field=models.CharField(choices=[('agep', "Selement les membres d'une unité"), ('all', 'Tous les utilisateurs')], default='agep', max_length=64, verbose_name='Accès'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/files/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='group',
            field=models.CharField(choices=[('accounting', 'Finances'), ('cs', 'Informatique'), ('misc', 'Divers')], default='misc', max_length=64, verbose_name='Groupe'),
        ),
        migrations.AlterField(
            model_name='filelogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='filelogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homepagenews',
            name='status',
            field=models.CharField(choices=[('0_draft', 'Brouillon'), ('1_online', 'En ligne'), ('2_archive', 'Archivé')], default='0_draft', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepagenewslogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='homepagenewslogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homepagenewsviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(default='fa-external-link-square', max_length=128, verbose_name='Icone FontAwesome'),
        ),
        migrations.AlterField(
            model_name='link',
            name='leftmenu',
            field=models.CharField(blank=True, choices=[('/main/top', 'Principal / En haut'), ('/main/bottom', 'Principal / En bas'), ('/admin/', 'Admin'), ('/gens/', 'Gens'), ('/communication/', 'Communication'), ('/logistics/', 'Logistique'), ('/logistics/vehicles', 'Logistique / Véhicules'), ('/logistics/rooms', 'Logistique / Salles'), ('/logistics/supply', 'Logistique / Matériel'), ('/units/', 'Unités et Accreds'), ('/accounting/', 'Finances'), ('/accounting/accounting', 'Finances / Compta'), ('/accounting/tools', 'Finances / Outils'), ('/accounting/proofs', 'Finances / Justifications'), ('/accounting/gestion', 'Finances / Gestion'), ('/cs/', 'Informatique'), ('/misc/', 'Divers')], help_text="Laisser blanc pour faire un lien normal. Réservé au comité de l'AGEPoly. Attention, cache de 15 minutes !", max_length=128, null=True, verbose_name='Position dans le menu de gauche'),
        ),
        migrations.AlterField(
            model_name='linklogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='linklogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signabledocument',
            name='file',
            field=models.FileField(upload_to='uploads/signable_document/'),
        ),
        migrations.AlterField(
            model_name='signabledocumentlogging',
            name='what',
            field=models.CharField(choices=[('imported', 'Importé depuis Truffe 1'), ('created', 'Creation'), ('edited', 'Edité'), ('deleted', 'Supprimé'), ('restored', 'Restauré'), ('state_changed', 'Statut changé'), ('file_added', 'Fichier ajouté'), ('file_removed', 'Fichier supprimé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='signabledocumentlogging',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signabledocumentviews',
            name='who',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
